### ISSUE TITLE
rabbitmq is installed/deployed even when transport is set as kafka

### ISSUE THREAD

**Issue by berndtj** [vmware/dispatch#471]
## Bug Report
Using the following config:
```yaml
ingress:
  serviceType: LoadBalancer
apiGateway:
  serviceType: LoadBalancer
  host: ***.dispatchframework.io
letsEncrypt:
  email: user@example.com
  staging: false
  route53:
    accessKeyID: *****
dispatch:
  host: ***.dispatchframework.io
  port: 443
  image:
    tag: dev-1527022552
  tls:
    ca: letsEncrypt
    secretName: radio-demo-02-tls
  faas: openfaas
  eventTransport: kafka
  bootstrapUser: bjung@vmware.com
  imageRegistry:
    name: ***
    username: ***
    password: ***
  oauth2Proxy:
    provider: github
    clientID: ***
    clientSecret: ***
```

Rabbitmq is still installed:

```
$ kubectl -n dispatch get pods
NAME                                                     READY     STATUS    RESTARTS   AGE
alertmanager-7c5f96bcd7-kpglz                            1/1       Running   0          7m
api-gateway-kong-6c57988dc-mls8x                         1/1       Running   1          13m
dispatch-api-manager-68bb9d4d96-nqrqf                    1/1       Running   0          5m
dispatch-application-manager-5847444f95-vntg2            1/1       Running   0          5m
dispatch-echo-server-59484bdbc8-7x6c2                    1/1       Running   0          5m
dispatch-event-manager-7b67894bf8-474wp                  1/1       Running   0          5m
dispatch-function-manager-c9d7c9686-fmd8w                2/2       Running   0          5m
dispatch-identity-manager-5686c64f79-4n7tl               2/2       Running   0          5m
dispatch-image-manager-85748985f7-ndj5j                  2/2       Running   0          5m
dispatch-rabbitmq-74cb98c9bc-2pg2k                       1/1       Running   1          5m
dispatch-secret-store-869b69f69d-f4cll                   1/1       Running   0          5m
dispatch-service-manager-bf4b8fddf-4jgw8                 1/1       Running   0          5m
faas-netesd-5f5474fc64-ct7l2                             1/1       Running   0          7m
gateway-695c7f5fc-c4xr6                                  1/1       Running   0          7m
ingress-nginx-ingress-controller-6bd74bd95f-f6sb5        1/1       Running   0          22m
ingress-nginx-ingress-default-backend-5f5888cc9b-dh7c8   1/1       Running   0          22m
postgres-postgresql-6f796d7df8-7lfcz                     1/1       Running   0          13m
prometheus-64c7c7b6bc-qtpt4                              1/1       Running   0          7m
transport-kafka-68b986865b-rt7w8                         1/1       Running   2          7m
transport-zookeeper-85fc6df85c-clslq 
```

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

### Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):
